### ISSUE TITLE
'noIntrinsicMetric' has been renamed to 'UIViewNoIntrinsicMetric'

### ISSUE THREAD

**Issue by ppshein** [ALoginov/ALLoadingView#14]
Current version is not compatible to swift 4.2 yet. I've found following error when I've upgrade my cocapods version.

**'noIntrinsicMetric' has been renamed to 'UIViewNoIntrinsicMetric'**
`private var blankIntrinsicContentSize = CGSize(width: UIView.noIntrinsicMetric, height: UIView.noIntrinsicMetric)`

 **'sendSubviewToBack' has been renamed to 'sendSubview(toBack:)'**
`stackView.sendSubviewToBack(backgroundView)`

**'noIntrinsicMetric' has been renamed to 'UIViewNoIntrinsicMetric'**
`if view.intrinsicContentSize.width == UIView.noIntrinsicMetric {`

**'init(style:)' has been renamed to 'init(activityIndicatorStyle:)'**
`let activityIndicator = UIActivityIndicatorView(style: UIActivityIndicatorView.Style.white)`

**Comment by ALoginov** [comment]
Hi, ppshein. Thanks for the information. Xcode didn't notify me on these issues during swift version update. Can you also link your version of cocoapods for me to check, thanks!

**Comment by ppshein** [comment]
> Hi, ppshein. Thanks for the information. Xcode didn't notify me on these issues during swift version update. Can you also link your version of cocoapods for me to check, thanks!

Hi,

```
cocapods version = 1.5.3
swift = 4.2
```

Currently, my swift language version in Xcode is selected 3 now. Build Settings > Swift Language Version > 3. Should I change to 4.2 instead?

**Comment by ALoginov** [comment]
> Currently, my swift language version in Xcode is selected 3 now. Build Settings > Swift Language Version > 3. Should I change to 4.2 instead?

Looks like it. Xcode probably incorrectly suggests you to update code to suit Swift 3 notation.
