### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by rayyagelski** [ALoginov/ALLoadingView#16]
If ALLoadingView is already appeared, before it is disappeared, I try to show it again, app crash.

ALLoadingView Presentation Error. Trying to push loading view while there is one already presented.

Can you make it to not crash?

**Comment by ALoginov** [comment]
Hi rayyagelski,

Animation block should be completed in order to remove the loading view from window's subviews. You can either set animation duration to 0.0 or use the completion block to show another loading view right after the first one.
