### ISSUE TITLE
Cancel option with progress

### ISSUE THREAD

**Issue by iFreedive** [ALoginov/ALLoadingView#3]
Hi

Would it be possible to have another loading type of progressWithCancelButton?

**Comment by ALoginov** [comment]
Hi

Yeah, will add this one. Thinking of adding support for custom controls, I assume not many people like using standard controls :)

**Comment by iFreedive** [comment]
Thanks

Im not so bothered about custom controls, works well for me as is, a nice clean approach.
Maybe the only thing I would say would be nice, is to be able to display a success or failure icon with optional text.

**Comment by ALoginov** [comment]
Thanks again for your suggestion. Have added progressWithCancelButton as a type in 1.1.1 release. Success/Failure messages will be added later
