### ISSUE TITLE
progressWithCancelButton has a lot of bugs

### ISSUE THREAD

**Issue by gerchicov-bp** [ALoginov/ALLoadingView#5]
1)cancel button doesn't work in fullscreen mode
2)the app falls down at all in windowed mode

**Comment by ALoginov** [comment]
Hi! 

Can you provide some info on your crashes? Are you sure that's not an assert check for content size? I've updated pod to version 1.1.3, maybe it will provide more info on your issue or fix it completely. 

Artem.
