### ISSUE TITLE
ALLoadingView ofType .messageWithIndicatorAndCancelButton has broken "Loading" label

### ISSUE THREAD

**Issue by nyekimov** [ALoginov/ALLoadingView#6]
ALLoadingView ofType .messageWithIndicatorAndCancelButton has broken "Loading" label. See attached image. Tested on the iPhone 5S simulator.
![desctop screenshot](https://cloud.githubusercontent.com/assets/1243986/23527953/9b8f41bc-ff5d-11e6-8ee6-c0b841c0875c.png)

**Comment by ALoginov** [comment]
Hi nyekimov. 
Looks like there is not enough space to fit content. You have many options:

1. Decrease message font size: 'messageFont' property
2. Decrease item spacing value. Basic is 30 pixels
3. Increase windowRatio. Default is 0.4, that's 40% of smallest side, width in portrait mode. Pretty small view on 4 inch screens.

**Comment by nyekimov** [comment]
@ALoginov I used the code from readme, shouldn't builtin code work just out of the box? 

And if you checkout SVProgressHUD it resizes automatically even if you supply custom message.

Anyway thanks, will keep using SVProgressHUD, was looking for a swift solution but yours yet doesn't fit my requirements.

**Comment by ALoginov** [comment]
@nyekimov Will think of adjusting content size for message labels. Thanks for contributing!
