### ISSUE TITLE
Custom appearance of UI elements

### ISSUE THREAD

**Issue by MattiaConfalonieri** [ALoginov/ALLoadingView#9]
Hi, great library, but I have some questions:

• Is possibile change the title of callback button?
• Is posible change the spinner color or style?
• Why blurred image have a mandatory grey background?

Thanks for reply

**Comment by ALoginov** [comment]
Hi! Thanks for response. 

As you can see from public methods, there is no way to edit button title, even set localised string. So, I guess, the only way to edit all the appearance attributes you mention is to copy source files directly. Just one file there. 

I'm pretty sure I'll continue to work on this item, I'm actually using it. Check for updates (pretty rare ones, I know).

**Comment by MattiaConfalonieri** [comment]
Ok thanks, I am not a big developer, but If I can maybe I make some Pull request with new features
